### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by brownbl1** [DVLP/run-func#2]
I get the following when running a script via npm on linux:

`/usr/bin/env: ‘node\r’: No such file or directory`

My script in the `package.json` is as follows:

`"myScript": "run-func scripts/myScript.js myArg"`

Upone inspecting `node_modules/run-func/index.js` I see that the file is CRLF instead of unix style line endings (just LF). After cloning the repo though, it appears they are in LF on my local machine. So I am not sure if this is due to the build pipeline / packaging step or if this is a git repository issue. But it seems the solution to this problem is to make sure that the file is converted to LF format.

**Comment by DVLP** [comment]
Merged  https://github.com/DVLP/run-func/pull/3 and published under 1.0.4

**Comment by jkahlina** [comment]
Nice, thanks @DVLP !

I just tested out the 1.0.4 version, but I still get the same error mentioned in this issue.

When you published, was it from a clean checkout of the code? I think the line ending normalization of local repositories happens on checkout.

I could also very much be out to lunch on this though :smile:

**Comment by DVLP** [comment]
Ok. Bumped and republished. Initially git changed them to CRLF but then after checking out again they stayed at LF.

**Comment by jkahlina** [comment]
Perfect: version 1.0.5 works!

Thanks!

**Comment by DVLP** [comment]
Cool, thanks for the PR
