### ISSUE TITLE
New ESM updates are breaking regular node usage

### ISSUE THREAD

**Issue by hafley66** [DVLP/run-func#7]
We are using older node, and the syntax for dynamic import throws parse error. 

Can you please publish a 2.0 stating the supported node versions?

Or load that import syntax lazily with new file for running import, by loading it with a require call

**Comment by DVLP** [comment]
What's the error, which Node version?

**Comment by hafley66** [comment]
sure thing, node 8/10 


```bash
.../node_modules/run-func/index.js:17
import('file://' + path.resolve(path.join(process.cwd(), process.argv[2]))).then((userModule) => {
^^^^^^



SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:607:28)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3
```

**Comment by DVLP** [comment]
Fixed deployed in 1.1.5

**Comment by DVLP** [comment]
Looks like version 2 will be needed in the end but to confirm are you seeing the problem in version 10? I see that version 10 is fine

**Comment by DVLP** [comment]
Fixed, may need clearing npm cache in old Node for npx to see the new version

**Comment by hafley66** [comment]
Thank you so much! Its probably node 8, we are very behind. I am on my way to fix it lol, but I was not original creator of these processes so I just have not gotten to it
