### ISSUE TITLE
Treat .js as esm when package type is module

### ISSUE THREAD

**Issue by melnikaite** [DVLP/run-func#8]
It'd be nice to improve detecting es6 modules by also checking in package json {"type": "module"}. In this case file extension could be .js.

**Comment by DVLP** [comment]
Node does not allow native import/export in regular *.js files, they must be *.mjs. Supporting package.json and *.js files as modules would require processing the project with a bundler. That's out of scope of run-func which is a very lean tool with no dependencies.

**Comment by melnikaite** [comment]
Node support this under flags ` --experimental-modules --es-module-specifier-resolution=node`

**Comment by DVLP** [comment]
Oh no, there goes another half day of my productive work. Anyway, published as 2.1.0. It seems like detecting type=module in package.json of the script directory and using dynamic import() does the job without any extra flags

**Comment by melnikaite** [comment]
I've tried the new release and noticed that detection of `package.json` doesn't work for me
I'm using npm script `"premigrate": "run-func src/libs/db.js createDatabase",`
`packageJsonPath` in my case is `/projects/p/src/libs/package.json`, but should be `/projects/p/package.json`
This definition `const packageJsonPath = path.resolve('package.json')` helped
I'll appreciate if you create one more release fixing this as well

**Comment by DVLP** [comment]
This means importing package.json from where the script is being executed not where the target file is located. Instead I made this traverse up and stop on first package.json found. Deployed as version 3, hopefully no new bugs as this is now more complicated. Version 3 also supports local modules as in(must be installed) https://github.com/DVLP/run-func/issues/4

**Comment by melnikaite** [comment]
Interesting solution)
Thanks a lot, Pawel, for all your efforts, now it works out of the box 👍
